# 公共配置文件
# @author stephen qiu
spring:
  application:
    name: trajectory-backend
  # 默认 dev 环境
  config:
    activate:
      on-profile: default
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 缓存
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  # session 配置
  session:
    # 开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: ${dev.mysql.datasource.driver-class-name}
    url: ${dev.mysql.datasource.url}
    username: ${dev.mysql.datasource.username}
    password: ${dev.mysql.datasource.password}
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: ${dev.redis.database}
    host: ${dev.redis.host}
    port: ${dev.redis.port}
    timeout: ${dev.redis.timeout}
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  elasticsearch:
    uris: ${dev.elasticsearch.uris}
  # RabbitMQ配置
  rabbitmq:
    # todo 是否开启RabbitMQ（预先关闭）
    enable: false
    host: ${dev.rabbitmq.host}
    port: ${dev.rabbitmq.port}
    username: ${dev.rabbitmq.username}
    password: ${dev.rabbitmq.password}
    max-await-timeout: 3000
    # 虚拟主机
    virtual-host: /

    # 消息确认（ACK）
    publisher-confirm-type: correlated #确认消息已发送到交换机(Exchange)
    publisher-returns: true #确认消息已发送到队列(Queue)
    template:
      mandatory: true
    # 是否手动ACK
    listener:
      type: simple
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 腾讯云COS对象存储配置
# todo 是否开启
cos:
  client:
    enable: true
    accessKey: ${dev.cos.client.accessKey}
    secretKey: ${dev.cos.client.secretKey}
    region: ${dev.cos.client.region}
    bucket: ${dev.cos.client.bucket}

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    description: "StephenQiu的接口文档信息。"
    concat: "Stephen Qiu"
    email: "popcornqhd@gmail.com"
    url: "https://github.com/Stephenqhd30"
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.stephen.trajectory.controller

# 对象存储配置
oss:
  # MinIO OSS配置
  minio:
    # todo 是否开启
    enable: false
    # 域名（格式：【ip:port】）
    endpoint: 127.0.0.1:9000
    # 是否开启TLS
    enable-tls: false
    # 用户的 SecretId
    secret-id: xxxxxxxx
    # 用户的 SecretKey
    secret-key: xxxxxxxx
    # 桶名称
    bucket-name: xxxxxxxx


# 讯飞星火api
xunfei:
  client:
    appid: ${dev.xunfei.client.appid}
    api-key: ${dev.xunfei.client.api-key}
    api-secret: ${dev.xunfei.client.api-secret}
